# Generated by Django 3.0 on 2020-07-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_area',
            new_name='restro_area',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_content',
            new_name='restro_contact',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_email',
            new_name='restro_email',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_id',
            new_name='restro_id',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_name',
            new_name='restro_name',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_otp',
            new_name='restro_otp',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_password',
            new_name='restro_password',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_status',
            new_name='restro_status',
        ),
        migrations.RenameField(
            model_name='restaurantmodel',
            old_name='resto_type',
            new_name='restro_type',
        ),
    ]
